### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by xsnrg** [dkreutzer/openhab2-bindings#1]
Daniel, thanks for the repo.  Any chance you could also create a release jar file?  My dev environment is currently not operational.

Thanks!

**Comment by dkreutzer** [comment]
There you go: https://github.com/dkreutzer/openhab2-bindings/releases 
Hope that helps

**Comment by dkreutzer** [comment]
There you go: https://github.com/dkreutzer/openhab2-bindings/releases 
Hope that helps
